export const SET_WALLET_DETAILS = "SET_WALLET_DETAILS";
export const SET_TRANSACTION_HISTORY = "SET_TRANSACTION_HISTORY";
export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";
